import express from "express";
const AuthMiddleware = require("../middlewares/AuthMiddleware");
import { services } from "../config/containerConfig";
import { createCrudController } from "../controllers/CrudController";
const ProductSearchController = require("../controllers/ProductSearchController");
const ProductImageController = require("../controllers/ProductImageController");
import ProductSearchService = require("../services/ProductSearchService");
import ImageService = require("../services/ImageService");
import { validate } from "../middlewares/ZodValidationMiddleware";
import { productCreateSchema, productUpdateSchema } from "../validations/schemas";

const router = express.Router();
const controller = createCrudController(services.product, "Products");
const searchController = new ProductSearchController(new ProductSearchService());
const imageController = new ProductImageController(services.product, ImageService);
const protect = AuthMiddleware.verifyToken.bind(AuthMiddleware);
const adminOnly = AuthMiddleware.requireRole("ADMIN");
router.get("/search", searchController.search.bind(searchController));
router.post("/:id/image", protect, adminOnly, imageController.upload.bind(imageController));
router.get("/", controller.findAll);
router.get("/:id", controller.findById);
router.post("/", protect, adminOnly, validate(productCreateSchema), controller.create);
router.put("/:id", protect, adminOnly, validate(productUpdateSchema), controller.update);
router.delete("/:id", protect, adminOnly, controller.delete);
module.exports = router;
