const categories = [
	["Pizzas tradicionais", "Sabores clássicos da casa"],
	["Pizzas especiais", "Combinações especiais da Pizza Express"],
	["Pizzas vegetarianas", "Opções com ingredientes frescos"],
	["Pizzas premium", "Ingredientes selecionados e sabores sofisticados"],
	["Pizzas doces", "Pizzas doces para finalizar a refeição"],
	["Lanches", "Lanches artesanais preparados na hora"],
	["Porções", "Porções para compartilhar"],
	["Bebidas", "Bebidas geladas para acompanhar"],
].map(([name, description]) => ({ name, description }));

const products = [
	["Margherita", "Molho de tomate, muçarela e manjericão", 3500, "Pizzas tradicionais"],
	["Calabresa", "Calabresa, cebola e muçarela", 3900, "Pizzas tradicionais"],
	["Portuguesa", "Presunto, ovos, cebola, ervilha e muçarela", 4400, "Pizzas tradicionais"],
	["Frango com Catupiry", "Frango desfiado, milho e Catupiry", 4700, "Pizzas tradicionais"],
	["Pepperoni Especial", "Pepperoni artesanal, muçarela e orégano", 5600, "Pizzas especiais"],
	["Bacon com Cebola", "Bacon crocante, cebola caramelizada e muçarela", 5900, "Pizzas especiais"],
	["Frango Cremoso", "Frango, cream cheese, milho e muçarela", 5700, "Pizzas especiais"],
	["Carne Seca com Catupiry", "Carne seca desfiada, cebola e Catupiry", 6500, "Pizzas especiais"],
	["Vegetariana", "Abobrinha, berinjela, tomate, cebola e muçarela", 4900, "Pizzas vegetarianas"],
	["Palmito", "Palmito, tomate, cebola e muçarela", 5000, "Pizzas vegetarianas"],
	["Caprese", "Tomate, muçarela de búfala, manjericão e pesto", 5700, "Pizzas vegetarianas"],
	["Brócolis com Catupiry", "Brócolis, alho, Catupiry e muçarela", 5200, "Pizzas vegetarianas"],
	["Parma com Brie", "Presunto de Parma, queijo brie e geleia de figo", 7800, "Pizzas premium"],
	["Camarão Cremoso", "Camarão, cream cheese, alho-poró e muçarela", 8900, "Pizzas premium"],
	["Cogumelos Trufados", "Cogumelos, azeite trufado e parmesão", 8200, "Pizzas premium"],
	["Filé Mignon", "Filé mignon, cebola roxa e Catupiry", 8500, "Pizzas premium"],
	["Chocolate com Morango", "Chocolate ao leite e morangos frescos", 5200, "Pizzas doces"],
	["Banana com Canela", "Banana, açúcar, canela e leite condensado", 4400, "Pizzas doces"],
	["Romeu e Julieta", "Goiabada cremosa e muçarela", 4600, "Pizzas doces"],
	["Prestígio", "Chocolate, coco ralado e leite condensado", 4900, "Pizzas doces"],
	["X-Burger", "Hambúrguer, queijo, alface, tomate e molho especial", 3200, "Lanches"],
	["X-Salada", "Hambúrguer, queijo, presunto, alface e tomate", 3500, "Lanches"],
	["Hot Dog Especial", "Salsicha, purê, milho, batata palha e cheddar", 2800, "Lanches"],
	["Sanduíche de Frango", "Frango desfiado, queijo, alface e molho especial", 3300, "Lanches"],
	["Batata Frita", "Porção de batata frita crocante", 2200, "Porções"],
	["Batata com Cheddar", "Batata frita com cheddar cremoso e bacon", 3200, "Porções"],
	["Anéis de Cebola", "Porção de anéis de cebola empanados", 2500, "Porções"],
	["Nuggets", "Porção de nuggets de frango", 2700, "Porções"],
	["Coca-Cola Lata", "Refrigerante Coca-Cola  lata 350 ml", 650, "Bebidas"],
	["Guaraná Lata", "Refrigerante Guaraná lata 350 ml", 600, "Bebidas"],
	["Água Mineral", "Água mineral sem gás 500 ml", 400, "Bebidas"],
	["Suco de Laranja", "Suco de laranja  natural 500 ml", 900, "Bebidas"],
	["Coca-Cola 2L", "Refrigerante Coca-Cola garrafa 2 litros", 1250, "Bebidas"],
	["Cerveja Long Neck", "Cerveja long neck 330 ml", 950, "Bebidas"],
].map(([name, description, base_price, category_name], index) => ({
	name,
	description,
	base_price,
	category_name,
	highlighted: [0, 4, 8, 12, 16, 20, 24, 28].includes(index),
}));

module.exports = {
	admin: { name: "Administrador", email: "admin@pizzaexpress.com", password: "Admin@123" },
	customers: ["Rafael Oliveira", "Mariana Costa", "Lucas Almeida", "Beatriz Santos", "Gabriel Ferreira", "Camila Rocha", "Joao Martins", "Larissa Souza", "Pedro Henrique", "Juliana Lima", "Thiago Ribeiro", "Fernanda Alves"].map((name, index) => ({
		name,
		email: index === 0 ? "cliente@pizzaexpress.com" : `cliente${index + 1}@pizzaexpress.com`,
		password: "Cliente@123",
	})),
	store: { id: 1, name: "Pizza Express", description: "Loja principal da Pizza Express", opening_hours: "18:00 às 23:00", delivery_fee: 700, min_order_value: 2000 },
	categories,
	products,
	sizes: [
		{ name: "Individual", code: "SMALL", description: "Pizza de 4 fatias, indicada para 1 pessoa", additional_price: 0 },
		{ name: "Média", code: "MEDIUM", description: "Pizza de 6 fatias, indicada para 2 pessoas", additional_price: 800 },
		{ name: "Grande", code: "LARGE", description: "Pizza de 8 fatias, indicada para 3 pessoas", additional_price: 1600 },
		{ name: "Família", code: "FAMILY", description: "Pizza de 12 fatias, indicada para 4 pessoas", additional_price: 2800 },
	],
	edges: [
		{ name: "Catupiry", description: "Borda recheada com Catupiry, para pizzas salgadas", additional_price: 800 },
		{ name: "Cheddar", description: "Borda recheada com cheddar, para pizzas salgadas", additional_price: 800 },
		{ name: "Cream Cheese", description: "Borda recheada com cream cheese, para pizzas salgadas", additional_price: 900 },
		{ name: "Chocolate", description: "Borda doce de chocolate, para pizzas doces", additional_price: 1000 },
	],
	additionals: [
		{ name: "Bacon Extra", description: "Porção extra de bacon", price: 700 },
		{ name: "Azeitona", description: "Porção extra de azeitona", price: 400 },
		{ name: "Milho", description: "Porção extra de milho", price: 300 },
		{ name: "Tomate Seco", description: "Porção extra de tomate seco", price: 600 },
		{ name: "Frango Extra", description: "Porção extra de frango desfiado", price: 800 },
		{ name: "Muçarela Extra", description: "Porção extra de muçarela", price: 700 },
		{ name: "Catupiry Extra", description: "Porção extra de Catupiry", price: 800 },
	],
};
